### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by tadinski** [madzadev/audio-player#1]
Rendering Player component in a Nextjs project results in this error

<img width="1017" alt="Screenshot 2021-05-04 at 18 39 06" src="https://user-images.githubusercontent.com/6358371/117038723-44c46f80-ad08-11eb-869d-ff463b7210dc.png">

Tried figuring out what this is related to, most likely to the encoding format. Maybe you have a clue what might solve this issue?

**Comment by madzadev** [comment]
Hi @tadinski! Thank you for reporting! 😉

In order to run it in NextJS, follow these 3 steps:
1. `npm i next-images next-transpile-modules`
2. create `next.config.js` in your project's root
3. paste this in that newly created config file:
```javascript
const withImages = require("next-images");
const withTM = require("next-transpile-modules")(["@madzadev/audio-player"]);

module.exports = withImages(withTM());
```

Sry for being late on this, hope this helps 😉

**Comment by madzadev** [comment]
Also, updated [docs](https://github.com/madzadev/audio-player) and patched [v.1.1.7](https://www.npmjs.com/package/@madzadev/audio-player), based on the issue 📄😉
