### ISSUE TITLE
[Issue]: npm/bun install not working for TypeScript

### ISSUE THREAD

**Issue by fvtrx** [madzadev/audio-player#13]
Hi @madzadev 
I tried to install this packages in my TypeScript project. But I'm facing the error below at the moment:

`Could not find a declaration file for module '@madzadev/audio-player'. '/Users/fvtrx/Documents/ProgrammingProject/syifa/node_modules/@madzadev/audio-player/dist/audio-player.js' implicitly has an 'any' type. Try npm i --save-dev @types/madzadev__audio-player if it exists or add a new declaration (.d.ts) file containing declare module '@madzadev/audio-player`

Can help to provide the declaration file for module `@madzadev/audio-player`?

Thanks.

**Comment by madzadev** [comment]
Hi there, @fvtrx ! Thanks for reporting!
Currently, the package does not provide support for TS, might consider doing a rewrite if I get enough requests! Thanks again!

**Comment by jason-heng** [comment]
we need a the types please
