### ISSUE TITLE
error with duration-of-audio number

### ISSUE THREAD

**Issue by tmratwork** [madzadev/audio-player#14]
instead of showing duration of the audio, what shows is the duration of the audio minus ten minutes. for example, screenshot below shows audio length of '1:34' but the actual audio length is '11:34' (eleven minutes and thirty four seconds). the audio not saved locally, it is in google cloud platform storage bucket.

am I implementing the audio-player incorrectly?

<img width="910" alt="image" src="https://github.com/madzadev/audio-player/assets/1439707/3142d001-8c9b-471b-9efd-074fd510bacd">

**Comment by madzadev** [comment]
Great catch, thanks for reporting! Should be fixed now with v2.1.13!

**Comment by tmratwork** [comment]
the update works! thank you :)

much appreciate you open sourcing your audio player and addressing issues.
