### ISSUE TITLE
add ability to adjust playback speed?

### ISSUE THREAD

**Issue by tmratwork** [madzadev/audio-player#15]
one of our users requested to slow down playback speed. some of the AI voices we use for generated guided meditations feel too fast. i think i can write this code, although i'm not skilled at coding.

1) any hints on what files i should focus on or how to do it?
2) are there guidelines you would like me to follow to make it easier to offer this feature for others (if you choose to bake it into the main project code)?
3) do i start by forking your project, and then uploading the modified code here?

thanks!

**Comment by tmratwork** [comment]
my colleague implemented this feature in our version of your audio-player. the audio-player now shows playback speed and has a slider to adjust playback speed from 0.5 to 2.5 (1 is normal). if you are interested, we can share the code with you. my colleague thinks you will probably not like his additions because it was a quick fix, and not robust as your code.

**Comment by madzadev** [comment]
Thanks for suggesting the feature and glad you found your solution for this!
I have used it temporarily for testing, but have not considered implementing it as a feature.

Maybe if I will get enough requests for this I would consider adding this.
