### ISSUE TITLE
Is there a way to get the current timestamp of the audio that's being played?

### ISSUE THREAD

**Issue by Babatunde13** [madzadev/audio-player#16]
So In my use case, I'm passing I can pass one or more track, but if the track passed is one, is there a way for me to get the current time stamp of the audio in millisecond?

**Comment by madzadev** [comment]
Hi there, thanks for using the audio player!
The time is handled in seconds in the `Time.jsx` component. If you want to get in ms you could customize it in `App.jsx` via `audio.currentTime` and log it to the console, for example.
