### ISSUE TITLE
peerDependencies do not support most recent version of react

### ISSUE THREAD

**Issue by BrianJenney** [madzadev/audio-player#2]
Currently using react >=17 in a project where I'm attempting to install audio-player. This library currently requires a peerDependency react version `^16.8`

`npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @madzadev/audio-player@1.1.9
npm ERR! node_modules/@madzadev/audio-player
npm ERR!   @madzadev/audio-player@"*" from the root project`

A possible fix is to specify a range of react versions to support:

`
"peerDependencies": {
    "react": "16 - 17"
}
`

**Comment by madzadev** [comment]
Thanks, @BrianJenney for the input!
Just tested with CRA, it works as expected. Just use `npm install @madzadev/audio-player --legacy-peer-deps`. See [docs](https://www.npmjs.com/package/@madzadev/audio-player?activeTab=readme) for more.
