### ISSUE TITLE
TypeError: Unsupported File Type

### ISSUE THREAD

**Issue by robbyph** [madzadev/audio-player#6]
Hey,

So, i'm using Next.Js and i think i have it setup right, but i was a little confused on how to add the config stuff since i already had stuff in my config file to begin with.

But, when i try and start the dev server, this is the error i get
```
error - ./node_modules/@madzadev/audio-player/dist/loop_current~becmfmpq.png
TypeError: unsupported file type: undefined (file: undefined)
```

Not 100% sure what's going on here, but it's had me stumped for like a few hours lol

**Comment by madzadev** [comment]
Hey, thanks for reporting!

You should be able to add your custom Next.js configuration as parameter.

```javascript
const withImages = require("next-images");
const withTM = require("next-transpile-modules")(["@madzadev/audio-player"]);

module.exports = withImages([withTM], {
  // ...
});
```
