### ISSUE TITLE
Adding a dynamic download button

### ISSUE THREAD

**Issue by PxlSyl** [madzadev/audio-player#7]
Hello!

Great player, one of the best I found. But there's some issues with the npm package, the icons and Next.js, so I digged into your code and tutorial in order to adapt to my website. BTW, is there a way to add a download button for the current playing track?

Also, a great improvment would be a typescript version :)

**Comment by mariosknl** [comment]
Hi @PxlSyl is it possible please to share a bit of your code or at least give me some guidance on how you added the icons in your NextJS project? I've managed to overcome some of the issues I was facing but yet the icons are missing and also the audio files never start playing. Any idea why this is happening please?

Thank you in advance for your time and effort

**Comment by PxlSyl** [comment]
Hi, might be too late... I re-writed all Madza's code in typescript and didn't use the package finally.

**Comment by madzadev** [comment]
@PxlSyl @mariosknl Just deployed v2, it should now support the images on the latest NextJS version without extra configuration, Tested on NextJS 14.1.0.
