### ISSUE TITLE
Next.js 13

### ISSUE THREAD

**Issue by thefubon** [madzadev/audio-player#8]
Can you please tell me how to install in Next 13?
And could you make documentation for Next.js with installation and setup separately playlist and player?

**Comment by adierwanto** [comment]
yea i curious too

**Comment by DaianaArena** [comment]
![image](https://github.com/madzadev/audio-player/assets/84255114/b85f4886-80b5-4e09-b50c-bebab7fec8b8)

I follow up the 'next' extra steps but the images still don't work.

**Comment by aaronch12Ch** [comment]
yo tengo el mismo problema

**Comment by aaronch12Ch** [comment]
¿como lo puedo soucionar @madzadev igual estoy utilizando nextjs y que no se reproduscan luego luego los audios si no hasta que le de yo play a la musica ?

**Comment by madzadev** [comment]
@thefubon @adierwanto @DaianaArena @aaronch12Ch Just deployed v2, to support the latest versions. Tested on React 18.2.0 and NextJS 14.1.0. This removed the use of the legacy tag for the npm command and extra configuration for NextJS.
