### ISSUE TITLE
 Jump to Next song when -> showPlaylist={false}

### ISSUE THREAD

**Issue by lpdraft** [madzadev/audio-player#9]
Hi Madza, 

Very nice to e-meet you.

I'm currenty using your audio player app. Unfortunatly, I'm unable to jump to next song when I set "showPlaylist={false}". In addition, I'm come across with 'url=undefined'. Is there any solution you can share?

Thanks a lot in advance

**Comment by madzadev** [comment]
Thanks for reporting @lpdraft ! Now fixed in v2.1.1.
